### ISSUE TITLE
[Help] Experiencing the same issue

### ISSUE THREAD

**Issue by R3DST0RM** [NoFrosty/template-errorbsdiff#1]
I stumbled upon your issue opened inside the bsdiff-node repository. I do experience the very same error, that Electron 20 causes build failures when the `bsdiff-node` library is used as a dependency.

Were you able to solve the issue?

**Comment by NoFrosty** [comment]
As @Brouilles said here Brouilles/bsdiff-node/issues/24:

The problem is not from [bsdiff-node](https://github.com/Brouilles/bsdiff-node), but in [Electorn](https://github.com/electron/electron) (only on actual version 20.X).

There is an issue for that: electron/electron/issues/35193.

So, for now I'm working on Electron@19 instead of 20.
